import { StyleSheet } from "react-native";

export default StyleSheet.create({
    todo:{
        backgroundColor:'#696969',
        height:130,
        borderRadius:20,
        margin:10,
      },
      button_passive:{
        height:40,
        paddingTop:5,
        marginLeft:10,
        marginRight:10,
        marginBottom:18,
        borderRadius:10,
        backgroundColor:'#212c33',
        alignItems:'center',
        justifyContent:'center',
      },
      button:{
        height:40,
        paddingTop:5,
        marginLeft:10,
        marginRight:10,
        marginBottom:18,
        borderRadius:10,
        backgroundColor:'orange',
        alignItems:'center',
        justifyContent:'center',
    
      },
      buttonText:{
        alignItems:'center',
        justifyContent:'center'
      },
      textinput:{
        marginLeft:15,
        marginTop:5,
        height:45,
        fontWeight:'bold'
      },
      seperator:{
      flex:1,
      borderTopWidth:1,
      marginLeft:15,
      marginRight:15,
      borderColor:'black',}
})